name: Node CI

on: [push]

jobs:
  lint:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v1
      - name: ESLint (JS/TS) Action 
        uses: tinovyatkin/action-eslint@v1
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}

  build:
    needs: [lint]
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout project
      uses: actions/checkout@v1
    - name: npm install, build and unit
      run: |
        npm ci
        npm run build
        npm test
